### PR TITLE
updated with multi-pumping applications

### PR DESCRIPTION
**Pull request by VELVETDETH**
Hi Paul,

I've integrated my multipumping snippets into this repo. You might take a look about the format and structure. 

P.S. It seems that there's a submodule that I can't clone

### CODE REVIEW

**Comment by paul-g** [comment]
Hey. I think we could do with only the ROM example, since it is complete (in the sense that there are 2 kernel blocks etc.) and it demonstrates the functionality entirely. Please remove the dot product example.

**Comment by VELVETDETH** [comment]
Hi Paul, I've removed that design.

**Comment by burchanie** [comment]
Hi,
It would be good to move your multipump directory into test/Infrastructure. That's the right place for code snippets which illustrate infrastructural features.
(Also, check out src/.../utils/Reductions.java)

**Comment by burchanie** [comment]
With the rest, it looks good to me. Paul, your call to or not to merge it.

**Comment by VELVETDETH** [comment]
Sorry for the mess...
@paul-g @burchanie I've revised my code as your request :)

**Pull request merged**
